/// <reference lib="webworker" />

// MyTaste service worker (vite-plugin-pwa `injectManifest` strategy).
//
// Ported faithfully from the legacy CRA Workbox SW (.pwa-legacy/service-worker.ts):
//   - precache + app-shell navigation fallback
//   - CacheFirst for same-origin images and /uploads
//   - NetworkFirst for /config.json and /api/config
//   - CacheFirst for the Font Awesome CDN + Google Fonts webfonts
//   - StaleWhileRevalidate for Google Fonts stylesheets
//   - StaleWhileRevalidate for /api/recipes and /api/recipe/* (maxEntries 150,
//     14 days, broadcast update)
//   - iOS-friendly deferred activation (SKIP_WAITING on demand) + recipes-updated
//     broadcast forwarding

import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { BroadcastUpdatePlugin } from 'workbox-broadcast-update';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Precache all the assets generated by the build. vite-plugin-pwa injects the
// manifest here (must be referenced literally for the inject step to find it).
precacheAndRoute(self.__WB_MANIFEST);

// App Shell-style routing: navigation requests are fulfilled with index.html so
// client-side routes work offline. Mirrors the legacy CRA exemptions.
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(({ request, url }: { request: Request; url: URL }) => {
  // If this isn't a navigation, skip.
  if (request.mode !== 'navigate') {
    return false;
  }

  // If this is a URL that starts with /_, skip.
  if (url.pathname.startsWith('/_')) {
    return false;
  }

  // If this looks like a URL for a resource (has a file extension), skip.
  if (url.pathname.match(fileExtensionRegexp)) {
    return false;
  }

  // Otherwise serve the app shell.
  return true;
}, createHandlerBoundToURL('/index.html'));

// Cache all same-origin images with CacheFirst — uploaded images are immutable
// per filename, so serving from cache is always safe.
// NOTE: Cross-origin recipe images (e.g. ${API_URL}/uploads/... on a different
// origin) cannot be intercepted by the SW. Requires an nginx proxy to make
// uploads same-origin.
registerRoute(
  ({ url, request }) =>
    request.mode !== 'navigate' &&
    url.origin === self.location.origin &&
    (url.pathname.endsWith('.png') ||
      url.pathname.endsWith('.jpg') ||
      url.pathname.endsWith('.jpeg') ||
      url.pathname.endsWith('.webp') ||
      url.pathname.startsWith('/uploads/')),
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  }),
);

// Cache /config.json so cold offline starts don't block on the fetch timeout.
registerRoute(
  ({ url, request }) => request.method === 'GET' && url.origin === self.location.origin && url.pathname === '/config.json',
  new NetworkFirst({ cacheName: 'config-json' }),
);

// Cache /api/config with NetworkFirst so a reconfigured server is always
// respected; falls back to cache only when the network is unreachable.
registerRoute(
  ({ url, request }) => request.method === 'GET' && url.origin === self.location.origin && url.pathname === '/api/config',
  new NetworkFirst({ cacheName: 'api-config' }),
);

// Cache Font Awesome CDN assets (icons used throughout the app).
registerRoute(
  ({ url }) => url.hostname === 'cdnjs.cloudflare.com',
  new CacheFirst({
    cacheName: 'cdn-assets',
    plugins: [new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  }),
);

// Cache Google Fonts stylesheets (short-lived, revalidate in background).
registerRoute(({ url }) => url.hostname === 'fonts.googleapis.com', new StaleWhileRevalidate({ cacheName: 'google-fonts-stylesheets' }));

// Cache Google Fonts webfont files (immutable — cache aggressively).
registerRoute(
  ({ url }) => url.hostname === 'fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  }),
);

// Runtime cache for both the list & single-recipe endpoints.
registerRoute(
  ({ url, request }) =>
    request.method === 'GET' &&
    url.origin === self.location.origin &&
    (url.pathname === '/api/recipes' || // full list
      url.pathname.startsWith('/api/recipe/')), // single recipe
  new StaleWhileRevalidate({
    cacheName: 'api-recipes',
    plugins: [
      new BroadcastUpdatePlugin(),
      // Only cache successful JSON responses — prevents HTML error pages
      // (e.g. 502/504 from nginx) from being stored and served as JSON.
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      // keep the cache neat: max 150 entries, purge after 2 weeks
      new ExpirationPlugin({
        maxEntries: 150,
        maxAgeSeconds: 14 * 24 * 60 * 60,
      }),
    ],
  }),
);

// When Workbox broadcasts an update, forward a simple vanilla event so the app
// can refresh its recipe data without a full reload.
self.addEventListener('message', (event) => {
  if (event?.data?.meta === 'workbox-broadcast-update' && event?.data?.payload?.cacheName === 'api-recipes') {
    self.clients.matchAll().then((clients) => clients.forEach((c) => c.postMessage({ type: 'recipes-updated' })));
  }
});

// Allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({ type: 'SKIP_WAITING' }). The plugin's
// registerSW wiring (see src/index.tsx) defers this until navigation so the
// user is never disrupted mid-session.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Diagnostic: log when the SW handles a recipes API fetch (cache vs network).
self.addEventListener('fetch', (event) => {
  if ((event as FetchEvent).request.url.includes('/api/recipes')) {
    console.debug('[SW] Handling /api/recipes fetch', (event as FetchEvent).request.url);
  }
});
