name: (Tags) – Test, Build & Push

on:
  push:
    tags: [ '*' ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  docker:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build \
            -t ghcr.io/melanx/mytaste-backend:${IMAGE_TAG} \
            -t ghcr.io/melanx/mytaste-backend:latest \
            ./backend
          
          docker push ghcr.io/melanx/mytaste-backend:${IMAGE_TAG}
          docker push ghcr.io/melanx/mytaste-backend:latest

      - name: Build & push frontend image
        run: |
          docker build \
            -t ghcr.io/melanx/mytaste-frontend:${IMAGE_TAG} \
            -t ghcr.io/melanx/mytaste-frontend:latest \
            ./frontend

          docker push ghcr.io/melanx/mytaste-frontend:${IMAGE_TAG}
          docker push ghcr.io/melanx/mytaste-frontend:latest
