name: (Latest) – Test, Build & Push

on:
  push:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  docker:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_TAG: dev

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build -t ghcr.io/melanx/mytaste-backend:${IMAGE_TAG} ./backend
          docker push ghcr.io/melanx/mytaste-backend:${IMAGE_TAG}

      - name: Build & push frontend image
        run: |
          docker build -t ghcr.io/melanx/mytaste-frontend:${IMAGE_TAG} ./frontend
          docker push ghcr.io/melanx/mytaste-frontend:${IMAGE_TAG}
