name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/melanx/mytaste-backend ./backend
          docker push ghcr.io/melanx/mytaste-backend

      - name: Build and push frontend image
        run: |
          docker build -f ./frontend/Dockerfile -t ghcr.io/melanx/mytaste-frontend .
          docker push ghcr.io/melanx/mytaste-frontend
