name: CI – Test, Build & Push

on:
  push:
    branches: [ main ]

jobs:
  # --------------------------------------------------
  # 1) Run the full test suite
  # --------------------------------------------------
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Test backend
        working-directory: ./backend
        run: |
          npm ci
          npm test -- --watchAll=false

  #      - name: Test frontend
  #        working-directory: ./frontend
  #        run: |
  #          npm ci
  #          npm test -- --watchAll=false

  # --------------------------------------------------
  # 2) Build & push images – only after tests succeed
  # --------------------------------------------------
  docker:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build -t ghcr.io/melanx/mytaste-backend:latest ./backend
          docker push ghcr.io/melanx/mytaste-backend:latest

      - name: Build & push frontend image
        run: |
          docker build -t ghcr.io/melanx/mytaste-frontend:latest ./frontend
          docker push ghcr.io/melanx/mytaste-frontend:latest
