name: run-tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # ----------------- backend -----------------
      - name: Install backend deps & run tests
        working-directory: ./backend
        run: |
          npm ci
          npm test -- --watchAll=false

      # ----------------- frontend ----------------
      - name: Install frontend deps & build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
